################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
logic/acceleration.obj: ../logic/acceleration.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/acceleration.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/alarm.obj: ../logic/alarm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/alarm.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/altitude.obj: ../logic/altitude.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/altitude.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/battery.obj: ../logic/battery.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/battery.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/bluerobin.obj: ../logic/bluerobin.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/bluerobin.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/clock.obj: ../logic/clock.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/clock.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/date.obj: ../logic/date.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/date.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/menu.obj: ../logic/menu.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/menu.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/rfbsl.obj: ../logic/rfbsl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfbsl.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/rfsimpliciti.obj: ../logic/rfsimpliciti.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfsimpliciti.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/stopwatch.obj: ../logic/stopwatch.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/stopwatch.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/temperature.obj: ../logic/temperature.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/temperature.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/test.obj: ../logic/test.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/test.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

logic/user.obj: ../logic/user.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/bin/cl430" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/smpl_nwk_config.dat" --cmd_file="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/configuration/End Device/smpl_config.dat"  -vmspx --abi=coffabi -O4 --opt_for_speed=0 --include_path="/opt/ti/ccsv6/ccs_base/msp430/include" --include_path="/opt/ti/ccsv6/tools/compiler/msp430_4.3.3/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/include" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/logic" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/driver" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/bluerobin" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Applications/application/End Device" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/drivers/code" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/bsp/mcus" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/radios/family5" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/mrfi/smartrf" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk" --include_path="/home/tomek/soft/ccs/workspace_v6_0/ez430_chronos/simpliciti/Components/nwk_applications" -g --define=__CC430F6137__ --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --diag_warning=225 --display_error_number --diag_wrap=off --silicon_errata=CPU18 --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU23 --silicon_errata=CPU40 --call_assumptions=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/user.pp" --obj_directory="logic" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


